[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[versions]
shadow = "9.4.1"
lombok = "1.18.46"
semver4j = "6.0.0"
luaj-jse = "3.0.1"
taffy = "1.1.4"
cssparser = "08121b9081dfea425038f76ee89307dda443d546" # 1.7.0
diffutils = "4.17"

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge = "26.2.0.87"
# https://projects.neoforged.net/neoforged/neoform
neoform = "26.2-2"
# https://projects.neoforged.net/neoforged/moddevgradle
moddev = "2.0.147"
# Fabric
# https://fabricmc.net/develop/
fabric-api = "0.160.0+26.2"
fabric-loader = "0.19.5"
fabric-loom = "1.17.19"
# https://modrinth.com/mod/modmenu/versions
fabric-modmenu = "20.0.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
semver4j = { module = "org.semver4j:semver4j", version.ref = "semver4j" }
luaj-jse = { module = "org.luaj:luaj-jse", version.ref = "luaj-jse" }
taffy = { module = "dev.vfyjxf:taffy", version.ref = "taffy" }
cssparser = { module = "com.github.xleavx:osbcp-css-parser", version.ref = "cssparser" }
diffutils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "diffutils" }
# Fabric
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-modmenu = { module = "com.terraformersmc:modmenu", version.ref = "fabric-modmenu" }